<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <PackageIcon>Logo.png</PackageIcon>
        <Description>A basic library for rotation development in FFXIV in RotationSolver.</Description>
        <PackageId>RotationSolverReborn.Basic</PackageId>
        <Title>RotationSolver.Basic</Title>
        <RepositoryUrl>https://github.com/FFXIV-CombatReborn/RotationSolverReborn/tree/main/RotationSolver.Basic</RepositoryUrl>
        <PackageRequireLicenseAcceptance>False</PackageRequireLicenseAcceptance>
        <PackageLicenseExpression>LGPL-3.0-or-later</PackageLicenseExpression>
        <PackageTags>FFXIV, FF14, Dalamud, Rotation</PackageTags>
        <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <GenerateDocumentationFile>True</GenerateDocumentationFile>
        <EnforceCodeStyleInBuild>False</EnforceCodeStyleInBuild>
        <Platforms>x64</Platforms>
		<CopyLocalLockFileAssemblies>False</CopyLocalLockFileAssemblies>
    </PropertyGroup>
    <PropertyGroup>
        <DalamudLibPath Condition="$([MSBuild]::IsOSPlatform('Windows'))">$(appdata)\XIVLauncher\addon\Hooks\dev\</DalamudLibPath>
        <DalamudLibPath Condition="$([MSBuild]::IsOSPlatform('Linux'))">$(HOME)/.xlcore/dalamud/Hooks/dev/</DalamudLibPath>
        <DalamudLibPath Condition="$([MSBuild]::IsOSPlatform('OSX'))">$(HOME)/Library/Application Support/XIV on Mac/dalamud/Hooks/dev/</DalamudLibPath>
        <DalamudLibPath Condition="$(DALAMUD_HOME) != ''">$(DALAMUD_HOME)/</DalamudLibPath>
        <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
        <SupportedOSPlatformVersion>10.0.17763.0</SupportedOSPlatformVersion>
		<EnableWindowsTargeting>true</EnableWindowsTargeting>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
      <NoWarn></NoWarn>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
      <NoWarn></NoWarn>
    </PropertyGroup>
    <ItemGroup>
        <Reference Include="Dalamud">
            <HintPath>$(DalamudLibPath)Dalamud.dll</HintPath>
            <Private>False</Private>
        </Reference>
	<Reference Include="Dalamud.Bindings.ImGui">
            <HintPath>$(DalamudLibPath)Dalamud.Bindings.ImGui.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="InteropGenerator.Runtime">
            <HintPath>$(DalamudLibPath)InteropGenerator.Runtime.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="Lumina">
            <HintPath>$(DalamudLibPath)Lumina.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="Lumina.Excel">
            <HintPath>$(DalamudLibPath)Lumina.Excel.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="FFXIVClientStructs">
            <HintPath>$(DalamudLibPath)FFXIVClientStructs.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="Newtonsoft.Json">
            <HintPath>$(DalamudLibPath)Newtonsoft.Json.dll</HintPath>
            <Private>False</Private>
        </Reference>

        <Using Include="System.ComponentModel" />
        <Using Include="Dalamud.Game.ClientState.JobGauge.Types" />

        <Using Include="Dalamud.Game.ClientState.Objects.Types" />

        <Using Include="RotationSolver.Basic" />
        <Using Include="RotationSolver.Basic.Actions" />
        <Using Include="RotationSolver.Basic.Attributes" />
        <Using Include="RotationSolver.Basic.Configuration.RotationConfig" />
        <Using Include="RotationSolver.Basic.Data" />
        <Using Include="RotationSolver.Basic.Helpers" />
        <Using Include="RotationSolver.Basic.Rotations" />
        <Using Include="RotationSolver.Basic.Rotations.Basic" />
        <Using Include="Dalamud.Game.ClientState.JobGauge.Enums" />
        <Using Include="Dalamud.Interface" />
        <Using Include="Dalamud.Bindings.ImGui" />
        <Using Include="Newtonsoft.Json" />

        <PackageReference Include="ECommons" Version="3.2.1.16" />

        <PackageReference Include="Microsoft.CodeAnalysis.BannedApiAnalyzers" Version="5.6.0">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <AdditionalFiles Include="$(SolutionDir)BannedSymbols.txt" />

        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.6.0" />

        <PackageReference Include="System.Drawing.Common" Version="10.0.10" />
        <ProjectReference Include="..\RotationSolver.SourceGenerators\RotationSolver.SourceGenerators.csproj" OutputItemType="Analyzer" ExcludeAssets="All" />

        <None Include="..\COPYING.LESSER">
            <Pack>True</Pack>
            <PackagePath>\</PackagePath>
        </None>
        <None Include="..\Images\Logo.png">
            <Pack>True</Pack>
            <PackagePath>\</PackagePath>
        </None>
        <PackageReference Include="Svg" Version="3.4.8" />
        <None Update="README.md">
            <Pack>True</Pack>
            <PackagePath>\</PackagePath>
        </None>
    </ItemGroup>
</Project>
