using System.Collections.Generic;

namespace RotationSolver.Basic.Configuration.RotationConfig
{
    /// <summary>
    /// Chinese (Simplified) translations for RotationConfig display names.
    /// </summary>
    internal static class RotationConfigCN
    {
        /// <summary>
        /// Cached language check; resolved once and reused.
        /// </summary>
        private static readonly Dictionary<string, string> _translations = new()
        {
            { "Allow Hissatsu Soten to be used on any target regardless of distance (good luck)", "允许必杀剑·九天无视距离对任意目标使用（祝你好运）" },
            { "Allow Mineuchi to be used on any target rather than just targets that already have Kuzushi status.", "允许刀背击打可用于任意目标，而非仅限于已有'崩'状态的目标" },
            { "Allow Sacred Soil while moving if fighting a boss", "与 Boss 战斗时允许移动中使用野战治疗阵" },
            { "Allow Uncoiled Fury and Writhing Snap to overwrite oGCDs when at range", "允许在远程时用蛇尾术/蛇袭覆盖能力技窗口" },
            { "Allow the use of Corpsacorps while moving (use at own risk).", "允许移动中使用交击斩（风险自负）" },
            { "Allow the use of high jump if there are enemies in melee range.", "允许近战范围内使用高跳" },
            { "Army's Paeon Uptime", "军神之歌持续时间" },
            { "Attempt to assign Raging Strikes, Battle Voice, and Radiant Finale to specific ogcd slots (Experimental)", "尝试将猛者、战斗之声和最终乐章分配到特定能力技窗口（实验性）" },
            { "Attempt to pool Black and White Mana for burst (Experimental)", "尝试为爆发积攒黑白魔力（实验性）" },
            { "Attempt to prevent bricking by allowing E.Prog at the end of GCD logic (experimental)", "尝试防止卡死：允许 GCD 逻辑末尾使用均衡预后（实验性）" },
            { "Attempt to weave Kunai's Bane/Trick attack second half of GCD (Disable if you miss weaving)", "尝试在 GCD 后半插入苦无之灾/背刺（如会失手请关闭）" },
            { "Auto Use Perfect Balance (aoe aggressive PB dump, turn me off if you don't want to waste PB in boss fight)", "自动使用震脚（AOE 激进倾泻，如不想在 Boss 战中浪费震脚请关闭）" },
            { "Auto Use Perfect Balance (single target full auto mode, turn me off if you want total control of PB)", "自动使用震脚（单体全自动模式，如想完全控制震脚请关闭）" },
            { "Auto Use Vril", "自动使用 Vril" },
            { "Automatically upgrade Horoscope with Helios/Aspected Helios", "自动用阳星/阳星相位升级天星冲日" },
            { "Average health threshold party members need to be to use Holos", "使用整体论时队员需要的平均 HP 阈值" },
            { "Average health threshold party members need to be to use Pneuma as an AOE heal", "使用魂灵风息进行 AOE 治疗时队员需要的平均 HP 阈值" },
            { "Average party HP percent needed to use Occult Elixir", "使用神秘灵液的队员平均 HP 阈值" },
            { "Average party HP percent to predict to heal instead of damage things", "小队平均 HP 低于此比例时，优先治疗而非输出" },
            { "Average party HP percent to predict to heal with judgement instead of damage things", "小队平均 HP 低于此比例时，优先使用判决治疗而非输出" },
            { "Average party HP percent to prioritize Indomitability and instant heals over heal-over-time effects", "小队平均 HP 低于此比例时，优先使用不屈不挠之策和瞬发治疗而非 HoT" },
            { "Average party HP percent to use Accession in HealAreaGCD", "AOE 治疗 GCD 中使用异界的波动的小队平均 HP 阈值" },
            { "Average party HP percent to use Accession in HealAreaGCD while moving and not under Emergency Tactics", "移动且不处于应急战术时，AOE 治疗 GCD 中使用异界的波动的小队平均 HP 阈值" },
            { "Average party HP percent to use Consolation", "使用慰藉的小队平均 HP 阈值" },
            { "Average party HP percent to use Emergency Tactics Succor in HealAreaGCD", "在 AOE 治疗 GCD 中使用应急战术士气高扬之策的小队平均 HP 阈值" },
            { "Average party HP percent to use Fey Blessing when Whispering Dawn or Angel's Whisper is missing", "没有低语黎明/天使的低语时使用仙子的祝福的小队平均 HP 阈值" },
            { "Average party HP percent to use Indomitability", "使用不屈不挠之策的小队平均 HP 阈值" },
            { "Average party HP percent to use Recitation with Indomitability (must be below AoE heal threshold)", "使用复诵不屈不挠之策的小队平均 HP 阈值（必须低于 AOE 治疗阈值）" },
            { "Average party HP percent to use Whispering Dawn or Angel's Whisper", "使用低语黎明/天使的低语的小队平均 HP 阈值" },
            { "Average party HP threshold to use Druochole", "使用灵橡清汁的队员平均 HP 阈值" },
            { "Average party HP threshold to use Ixochole", "使用寄生清汁的队员平均 HP 阈值" },
            { "Average party HP threshold to use Pepsis", "使用消化的队员平均 HP 阈值" },
            { "Average party HP threshold to use Physis", "使用自生的队员平均 HP 阈值" },
            { "Average party HP threshold to use Pneuma in Multi Targets", "多目标中使用魂灵风息的队员平均 HP 阈值" },
            { "Average party HP threshold to use Pneuma in Single Target", "单体中使用魂灵风息的队员平均 HP 阈值" },
            { "Average party HP threshold to use Taurochole", "使用白牛清汁的队员平均 HP 阈值" },
            { "Average party HP threshold to use Zoe on Pneuma (if lower) or Eukrasian Prognosis (if higher)", "使用活化+魂灵风息（较低 HP）或活化+均衡预后（较高 HP）的队员平均 HP 阈值" },
            { "BMR: Dump Heat before downtime (Experimental)", "BMR：停手前倾泻热量（实验性）" },
            { "Blood Gauge Strategy", "血债量谱策略" },
            { "Bloodwhetting/Raw intuition heal threshold", "原初的血气/原初的直觉治疗阈值" },
            { "Buff Alignment Timer (Experimental, do not touch if you don't understand it)", "爆发对齐计时器（实验性，如不理解请勿修改）" },
            { "Cast Reprise when moving with no instacast.", "移动且无瞬发时使用短兵相接" },
            { "Casting cost requirement for Thin Air to be used", "使用无中生有所需的魔法消耗阈值" },
            { "Choose Bard Song Timing Preset", "选择诗人歌曲时间预设" },
            { "Choose Opener Variation", "选择起手变体" },
            { "Choose Opener.", "选择起手" },
            { "Choose a Fight", "选择战斗" },
            { "Countdown Suiton queue time (change this to 5 if you can trust your teamm. Or it should be 4 or 3 to prevent 5s countdown bait)", "倒计时水遁预备时间（如果信任队友可改为5；建议4或3以避免5秒倒计时陷阱）" },
            { "Countdown opener configuration", "倒计时起手配置" },
            { "Custom Army's Paeon Uptime", "自定义军神之歌持续时间" },
            { "Custom Mage's Ballad Uptime", "自定义贤者叙事谣持续时间" },
            { "Custom Wanderer's Minuet Uptime", "自定义放浪神小步舞曲持续时间" },
            { "Custom Wanderer's Weave Slot Timing", "自定义放浪神插入时机" },
            { "Dance Partner Name (If empty or not found uses default dance partner priority)", "舞伴名称（留空或未找到则使用默认舞伴优先级）" },
            { "Define potion usage behavior for Dancer", "定义舞者爆发药使用行为" },
            { "Delay Prefulgence/Vice of Thorns for buff alignment (about 3 gcd after Embolden)", "延迟决断/荆棘之刑以对齐增益（鼓励后约 3 GCD）" },
            { "Detonate Earlthy Star when you have Giant Dominance", "拥有大宇宙主宰时引爆地星" },
            { "Disable Standard Step in Burst - Ignored if not high enough level for Finishing Move", "爆发中禁用标准舞步（等级不足以使用收尾舞步时忽略）" },
            { "Do not start Aetherpact if the target's HP is above this percentage (prevents toggling)", "目标 HP 超过此比例时不开启以太契约（防止频繁开关）" },
            { "Early moving Combust refresh", "提前刷新移动中的炽灼" },
            { "Enable Fight Presets? (Experimental)", "启用战斗预设？（实验性）" },
            { "Enable Potion Usage", "启用爆发药使用" },
            { "Enable PrepullHeartbreak Shot? - Use with BMR Auto Attack Manager", "启用预拉心痛击？（需配合 BMR 自动攻击管理器）" },
            { "Enable Sandbag Mode?", "启用木桩模式？" },
            { "Enable Swiftcast Restriction Logic to attempt to prevent actions other than Raise when you have swiftcast", "启用即刻限制逻辑：拥有即刻时仅允许使用复活" },
            { "Enable Swiftcast restriction: only allow Raise while Swiftcast is active", "启用即刻限制：即刻激活时仅允许复活" },
            { "Enable ballpark DoT time-to-kill estimator (in addition to normal TTK configs)", "启用大致 DOT 击杀时间估计器（附加于常规 TTK 配置）" },
            { "Enemy HP threshold needed to use burst oGCDs on if previous config disabled", "上一选项禁用时使用爆发能力技所需的敌方 HP 阈值" },
            { "Enemy health threshold needed for Perfectio use", "使用完美所需的敌方 HP 阈值" },
            { "Enemy health threshold needed for Smite use", "使用猛击所需的敌方 HP 阈值" },
            { "Equilibrium Heal Threshold", "泰然自若治疗阈值" },
            { "Estimated percent of HP dealt as DPS for ballpark calculations", "大致估算中 DPS 造成的 HP 百分比" },
            { "Experimental Pot Usage(used up to 5 seconds before SerpentsIre comes off cooldown)", "实验性爆发药使用（蛇灵之怒冷却结束前最多5秒使用）" },
            { "Extend Astral Fire time more conservatively (3 GCDs) (Default is 2 GCDs)", "更保守地延长星极火时间（3 GCD，默认为 2 GCD）" },
            { "First Song", "第一首歌" },
            { "For this many seconds after Presence of Mind starts, only use Afflatus Misery and Glare IV while actually moving", "神速咏唱开启后多少秒内，仅在确实移动时才使用苦难之心和闪灼 IV" },
            { "Freely use burst damage oGCDs", "自由使用爆发伤害能力技" },
            { "Guardian HP Threshold", "守护 HP 阈值" },
            { "Hallowed Guardian HP Threshold", "神圣领域+守护 HP 阈值" },
            { "Health threshold Kardion target needs to be to use Soteria", "心关目标需要使用拯救的 HP 阈值" },
            { "Health threshold for Cover (Set to 0 to disable)", "掩护使用的目标生命阈值（设为 0 禁用）" },
            { "Health threshold for Intervention (Set to 0 to disable)", "干预使用的目标生命阈值（设为 0 禁用）" },
            { "Health threshold for using Intervention to attempt to save someone", "使用干预救人的目标生命阈值" },
            { "Health threshold needed to use Tempura Coat", "使用天衣无缝所需的 HP 阈值" },
            { "Health threshold needed to use Tengentsu/ThirdEye outside of AOE mit scenarios.", "AOE 减伤场景之外使用天眼通/心眼所需的 HP 阈值" },
            { "Health threshold party member needs to be to use Krasis", "队员需要使用混合的 HP 阈值" },
            { "Health threshold party member needs to be to use Pneuma as a ST heal", "队员需要使用魂灵风息进行单体治疗的 HP 阈值" },
            { "Health threshold party member needs to be to use Soteria", "队员需要使用拯救的 HP 阈值" },
            { "Health threshold party member needs to be to use Taurochole", "队员需要使用白牛清汁的 HP 阈值" },
            { "Health threshold party member needs to be to use an OGCD Heal while not holding addersgal stacks", "没有蛇胆充能时，队员需要 OGCD 治疗的 HP 阈值" },
            { "Health threshold tank party member needs to use Krasis", "坦克队员需要使用混合的 HP 阈值" },
            { "Health threshold tank party member needs to use Pneuma as a ST heal", "坦克队员需要使用魂灵风息进行单体治疗的 HP 阈值" },
            { "Health threshold tank party member needs to use Pneuma as an AOE heal", "坦克队员需要使用魂灵风息进行 AOE 治疗的 HP 阈值" },
            { "Health threshold tank party member needs to use Zoe", "坦克队员需要使用活化的 HP 阈值" },
            { "Health threshold tank party member needs to use an OGCD Heal on Tanks while not holding addersgal stacks", "没有蛇胆充能时，坦克队员需要 OGCD 治疗的 HP 阈值" },
            { "Health threshold target needs to be to use Druochole", "目标需要使用灵橡清汁的 HP 阈值" },
            { "Health threshold target needs to be to use Taurochole", "目标需要使用白牛清汁的 HP 阈值" },
            { "Hold hammer chain for movement time (0/5/10/15s).", "为移动保留锤子连击时间（0/5/10/15 秒）" },
            { "Hold melee combo up to 2s if out of range", "超出范围时保留近战连击最多 2 秒" },
            { "Hold one charge of Uncoiled Fury after burst for movement", "爆发后保留一层蛇尾术用于移动" },
            { "Holds Standard Step if no targets in range (Warning, will drift & Buff may fall off)", "范围内无目标时保留标准舞步（警告：会偏移且增益可能消失）" },
            { "Holds Tech Step if no targets in range (Warning, will drift)", "范围内无目标时保留技巧舞步（警告：会偏移）" },
            { "How long has to pass on Serpents Ire's cooldown before the rotation starts pooling gauge for burst. Leave this alone if you dont know what youre doing. (Will still use Reawaken if you reach cap regardless of timer)", "蛇灵之怒冷却经过多少秒后开始积攒量谱准备爆发。不知道在做什么就别动。（达到上限仍会使用觉醒，不受计时器限制）" },
            { "How long on the status time for Hunt needs to be to allow reawaken use (setting this too low can lead to dropping buff)", "狩猎状态剩余多少秒时允许使用觉醒（设太低可能导致增益丢失）" },
            { "How long on the status time for Swift needs to be to allow reawaken use (setting this too low can lead to dropping buff)", "迅捷状态剩余多少秒时允许使用觉醒（设太低可能导致增益丢失）" },
            { "How many charges of Uncoiled Fury needs to be at before be used inside of melee (Ignores burst, leave at 3 to hold charges for out of melee uptime or burst only)", "近战范围内至少保留几层蛇尾术才使用（不受爆发限制，设为 3 则仅保留用于远程维持或爆发）" },
            { "How many seconds before combat starts to use Standard Finish?", "战斗开始前多少秒使用标准舞步结束？" },
            { "How many seconds before combat starts to use Standard Step?", "战斗开始前多少秒使用标准舞步？" },
            { "How many seconds before combat starts to use Technical Finish?", "战斗开始前多少秒使用技巧舞步结束？" },
            { "How many seconds before combat starts to use Technical Step?", "战斗开始前多少秒使用技巧舞步？" },
            { "How to control Deployment Tactics usage", "展开战术使用策略" },
            { "How to manage the last thin air charge", "如何管理最后一层无中生有" },
            { "How to use Aurora", "极光使用方式" },
            { "How to use Deployment Tactics", "展开战术使用方式" },
            { "How to use Heart Of Stone/Heart Of Corundum", "石之心/刚玉之心使用方式" },
            { "How to use pots", "爆发药使用方式" },
            { "If a party member's health drops below this percentage, the Regen healing ability will not be used on them", "队员 HP 低于此比例时，不对其使用再生类治疗技能" },
            { "Keep Defend on cooldown if you are at full stacks of Finishing Fervor", "终击狂热满层时保持防御冷却" },
            { "Keep at least 3000 MP", "保留至少 3000 MP" },
            { "Limit Liturgy Of The Bell to multihit party stacks", "限制礼仪之铃只在多次伤害时触发" },
            { "Limit Macrocosmos to multihit party stacks", "限制大宇宙只在多次伤害时触发" },
            { "Limit Panhaima to multihit party stacks", "限制泛输血只在多次伤害时触发" },
            { "Limit Seraphism to multihit party stacks", "限制炽天附体只在多次伤害时触发" },
            { "Lock healing actions while Macrocosmos is active", "大宇宙激活时锁定治疗技能" },
            { "Lower HP threshold you need to be to use Xenoglossy as a heal oGCD", "使用异言作为治疗能力技的自身 HP 下限" },
            { "MP Spending Strategy", "MP 消耗策略" },
            { "MP needed to use Blood Drain/Divination Rune for MP gain", "使用吸血/占卜符文回蓝所需的 MP 阈值" },
            { "Mage's Ballad Uptime", "贤者叙事谣持续时间" },
            { "Max distance you can be from target for Phantom Kick use (Danger, you will die)", "使用幻影踢的最大目标距离（危险，可能会死）" },
            { "Max distance you can be from the boss for Primal Rend use (Danger, setting too high will get you killed)", "使用蛮荒崩裂的最大 Boss 距离（危险，设置过高会致死）" },
            { "Max distance you can be from the target for Crimson Cyclone use", "使用猩红旋风的最大目标距离" },
            { "Max distance you need to be from the target for Dragonfire Dive useage", "使用龙炎冲的最大目标距离" },
            { "Max distance you need to be from the target for Stardiver useage", "使用坠星冲的最大目标距离" },
            { "Meikyo Shisui countdown timing.", "明镜止水倒计时时机" },
            { "Minimum Fairy Gauge required before prioritizing Fey Union (link)", "优先使用仙子的拥抱（联结）所需的最低妖精量谱" },
            { "Minimum HP percent allowed for the use of Devour as a heal", "允许使用大快朵颐治疗的最低 HP 百分比" },
            { "Minimum HP percent allowed for the use of Missile", "允许使用导弹的最低 HP 百分比" },
            { "Minimum HP percent to use Excogitation as a heal instead of a defensive buff", "将生命活性法用作治疗（而非防御增益）的最低 HP 百分比" },
            { "Minimum HP threshold among party member needed to pop Horoscope)", "引爆天星冲日所需的队员最低 HP 阈值" },
            { "Minimum HP threshold among party member needed to pop Microcosmos", "引爆小宇宙所需的队员最低 HP 阈值" },
            { "Minimum HP threshold among party member needed to use Horoscope", "使用天星冲日所需的队员最低 HP 阈值" },
            { "Minimum HP threshold party member needs to be to use Afflatus Solace at 0 Blood Lily stacks", "血百合 0 层时使用安慰之心的队员最低 HP 阈值" },
            { "Minimum HP threshold party member needs to be to use Afflatus Solace at 1 Blood Lily stack", "血百合 1 层时使用安慰之心的队员最低 HP 阈值" },
            { "Minimum HP threshold party member needs to be to use Afflatus Solace at 2 Blood Lily stacks", "血百合 2 层时使用安慰之心的队员最低 HP 阈值" },
            { "Minimum HP threshold party member needs to be to use Aspected Benefic", "使用吉星相位的队员最低 HP 阈值" },
            { "Minimum HP threshold party member needs to be to use Benediction", "使用天赐祝福的队员最低 HP 阈值" },
            { "Minimum HP threshold party member needs to be to use Clemency with Requiescat", "队员需要安魂深仁厚泽的最低 HP 阈值" },
            { "Minimum HP threshold party member needs to be to use Clemency without Requiescat", "队员需要普通深仁厚泽的最低 HP 阈值" },
            { "Minimum HP threshold party member needs to be to use Essential Dignity 2nd charge", "使用第 2 层先天禀赋的队员最低 HP 阈值" },
            { "Minimum HP threshold party member needs to be to use Essential Dignity 3rd charge", "使用第 3 层先天禀赋的队员最低 HP 阈值" },
            { "Minimum HP threshold party member needs to be to use Essential Dignity last charge", "使用最后一层先天禀赋的队员最低 HP 阈值" },
            { "Minimum HP threshold party member needs to be to use Synastry", "使用星位合图的队员最低 HP 阈值" },
            { "Minimum HP threshold party member needs to be to use Tetragrammaton 2nd charge", "使用第 2 层神名的队员最低 HP 阈值" },
            { "Minimum HP threshold party member needs to be to use Tetragrammaton last charge", "使用最后一层神名的队员最低 HP 阈值" },
            { "Minimum MP before prioritizing emergency healing and rezzing (willing to use Seraphism sooner)", "优先紧急治疗和复活的最低 MP（愿意更早使用炽天附体）" },
            { "Minimum average HP threshold among party members needed to detonate Earthly Star (when Giant Dominance)", "引爆地星所需的小队平均 HP 下限（有大宇宙主宰时）" },
            { "Minimum average HP threshold among party members needed to use Afflatus Rapture at 0 Blood Lily stacks", "血百合 0 层时使用狂喜之心所需的小队平均 HP 下限" },
            { "Minimum average HP threshold among party members needed to use Afflatus Rapture at 1 Blood Lily stacks", "血百合 1 层时使用狂喜之心所需的小队平均 HP 下限" },
            { "Minimum average HP threshold among party members needed to use Afflatus Rapture at 2 Blood Lily stacks", "血百合 2 层时使用狂喜之心所需的小队平均 HP 下限" },
            { "Minimum average HP threshold among party members needed to use Asylum", "使用庇护所所需的小队平均 HP 下限" },
            { "Minimum average HP threshold among party members needed to use Celestial Opposition (only when NOT holding Giant Dominance)", "使用天星冲日所需的小队平均 HP 下限（仅当没有大宇宙主宰时）" },
            { "Minimum average HP threshold among party members needed to use Cure III", "使用愈疗所需的小队平均 HP 下限" },
            { "Minimum average HP threshold among party members needed to use Lady Of Crowns", "使用王冠之贵妇所需的小队平均 HP 下限" },
            { "Minimum average HP threshold among party members needed to use Medica III / Medica II", "使用医养/医治所需的小队平均 HP 下限" },
            { "Minimum average party HP required before using single-target oGCDs on non-tanks", "对非坦克使用单体 OGCD 治疗所需的最低小队平均 HP" },
            { "Minimum health threshold party member needs to be to use Benediction", "使用天赐祝福的队员最低 HP 阈值" },
            { "Minimum movement time before allowing movement-based actions", "允许位移类技能的最小移动时间" },
            { "Minimum target distance for disengage fallback", "脱离回退的最小目标距离" },
            { "Nascent Flash Heal Threshold", "原初的勇猛治疗阈值" },
            { "Number of GCDs before you cap on blue lillies that overcap protection will consider 'near full'.", "蓝色百合溢出前视为'即将满'的 GCD 数量（用于溢出保护）" },
            { "Number of fewer mobs required to favor AoW spam over Bio (0 = use Bio if break-even below 30s)", "优先 AOW 倾泻而非毒菌所需少杀的怪物数量（0 = 如果 30 秒内持平则使用毒菌）" },
            { "Only use Benediction on tanks", "仅对坦克使用天赐祝福" },
            { "Only use DOTs on targets with Boss Icon", "仅对 Boss 图标目标使用 DOT" },
            { "Only use Deployment Tactics on Critical Shields?", "仅对暴击盾使用展开战术？" },
            { "Only use Embolden if in Melee range.", "仅在近战范围内使用鼓励" },
            { "Only use Fight or Flight while in melee range of an enemy", "仅在近战范围内使用战逃反应" },
            { "Only use Nascent Flash if Tank Stance is off", "仅在关闭坦克姿态时使用原初的勇猛" },
            { "Only use Occult Ether on self", "仅对自己使用神秘以太" },
            { "Only use Occult Potion on self", "仅对自己使用神秘灵药" },
            { "Only use Wildfire on Boss targets", "仅对 Boss 目标使用野火" },
            { "Opener/Burst open window (GCDs)", "起手/爆发窗口（GCD 数）" },
            { "Order", "顺序" },
            { "Paint overcap protection limit. How many paint you need to be at for it to use Holy out of burst (Setting is ignored when you have Hyperphantasia)", "颜料溢出保护限制：有多少颜料时在爆发外使用神圣（拥有超幻想时忽略此设置）" },
            { "Paint overcap protection.", "颜料溢出保护" },
            { "Party HP percent threshold to use Emergency Tactics with Succor", "使用应急战术+士气高扬之策的小队 HP 百分比阈值" },
            { "Personal health threshold needed for Earth's Reply use without hostiles nearby", "周围无敌方时使用大地响应所需的自身 HP 阈值" },
            { "Player HP percent needed to use Arkveld MegaPotion", "使用 Arkveld 大药水所需的自身 HP 百分比" },
            { "Player HP percent needed to use Occult Resuscitation", "使用神秘苏生所需的自身 HP 百分比" },
            { "Player HP percent needed to use Rathalos MegaPotion", "使用雄火龙大药水所需的自身 HP 百分比" },
            { "Player health threshold needed for Bloodbath use", "使用浴血所需的自身 HP 阈值" },
            { "Please note that this rotation is optimised for Lv100 high-end encounters. V&C/OC GCDs may break combo.\n", "请注意：此循环针对 100 级高难内容优化。多变/正统迷宫 GCD 可能断开连击。\n" },
            { "Please note that this rotation is optimised for combats that start with a countdown Rainbow Drip cast.\n", "请注意：此循环针对倒计时彩虹点滴起手的战斗优化。\n" },
            { "Please note that this rotation is optimised for high-end encounters (Only for countdown 8 people fights).\n", "请注意：此循环针对高难内容优化（仅适用于 8 人倒计时战斗）。\n" },
            { "Please note that this rotation is optimised for high-end encounters.\n", "请注意：此循环针对高难内容优化。\n" },
            { "Please note that this rotation is optimised for most fights. However, V&C/OC GCDs may break mudra.\n", "请注意：此循环针对大多数战斗优化。但多变/正统迷宫 GCD 可能断开忍术。\n" },
            { "Pool Black and White Mana for burst Embolden", "为鼓励爆发积攒黑白魔力" },
            { "Pool Shroud for Arcane Circle.", "为神秘环保留魂衣" },
            { "Potion Usage Preset", "爆发药使用预设" },
            { "Potion Usage Presets", "爆发药使用预设" },
            { "Prevent Higanbana use if theres more than one target", "多目标时禁止使用彼岸花" },
            { "Prevent healing during burst combos", "爆发连击期间禁止治疗" },
            { "Prevent raising during burst combos", "爆发连击期间禁止复活" },
            { "Prevent the use of defense abilties during burst", "爆发期间禁止使用防御技能" },
            { "Prevent the use of defense abilties during bursts", "爆发期间禁止使用防御技能" },
            { "Prioritise Aetherflow before Dissipation", "在转化之前优先以太超流" },
            { "Prioritize Essential Dignity over single target GCD heals when available", "可用时优先使用先天禀赋而非单体 GCD 治疗" },
            { "Prioritize Microcosmos over all other healing when available", "可用时优先使用大宇宙而非其他所有治疗" },
            { "Prioritize Viper buff application and refresh over Phantom GCDs", "优先保持和刷新蝰蛇增益而非使用幻影 GCD" },
            { "Raise while in solar bahamut", "日神巴哈姆特附体期间使用复活" },
            { "Refresh Death's Design with this many seconds remaining", "死亡烙印剩余这么多秒时刷新" },
            { "Regen on Tank at 5 seconds remaining on Prepull Countdown.", "起手倒计时剩余 5 秒时对坦克使用再生" },
            { "Remove Aetherpact if the linked party member's HP is above this percentage", "联结目标 HP 超过此比例时移除以太契约" },
            { "Restrict Dance Partner to only DPS targets if any", "如有 DPS 则限制舞伴仅为 DPS 目标" },
            { "Restrict GCD use if Serpent's Tail, Twinblood, or Twinfang oGCDs can be used", "当蛇尾术、双血或双牙能力技可用时限制 GCD 使用" },
            { "Restrict Tactician to only be allowed to be used when there are multiple hostile targets", "限制策动仅在有多个敌方目标时使用" },
            { "Restrict mitigations to not overlap", "限制减伤技能不重叠" },
            { "Save Phantom Attacks for class specific damage bonus?", "保留幻影攻击等职业专属伤害加成？" },
            { "Seconds you must be moving before Ruin II will be used", "需要移动多少秒后才使用毁坏" },
            { "Seconds you must be stationary before Sacred Soil can be used", "需要静止多少秒后才可放置野战治疗阵" },
            { "Select an opener", "选择起手" },
            { "Shadowbringer Threshold", "暗影使者使用阈值" },
            { "Simple Lord of Crowns logic (use under divinaiton)", "简化王冠之领主逻辑（在占卜中使用）" },
            { "Skip DOT check for Barrage usage", "使用连珠箭时跳过 DOT 检查" },
            { "Skip Magical Aversion check for Lost Burst and use it as AOE spam", "跳过魔法反感检查，将失传爆发作为 AOE 倾泻使用" },
            { "Skip Physical Aversion check for Lost Rampage and use it as AOE spam", "跳过物理反感检查，将失传暴怒作为 AOE 倾泻使用" },
            { "Soul Voice Threshold for Apex Arrow", "绝峰箭所需的灵魂之声阈值" },
            { "Spam Gobskin, keeping its status active", "持续使用哥布皮肤以维持状态激活" },
            { "Standard Step, Standard Finish & Finishing Move Hold Strategy", "标准舞步/结束/收尾舞步保留策略" },
            { "Suiton/Huton Prep Window (seconds before Trick Attack / Kunai's Bane)", "水遁/风遁预备窗口（背刺/苦无之灾前秒数）" },
            { "Target HP percent needed to use Occult Potion", "使用神秘灵药所需的目标 HP 百分比" },
            { "Target MP needed to use Occult Ether", "使用神秘以太所需的目标 MP" },
            { "Target health threshold needed to use Blackest Night with above option", "配合上述选项使用至黑之夜的目标生命阈值" },
            { "Target health threshold needed to use Oblation with above option", "配合上述选项使用献奉的目标生命阈值" },
            { "Technical Step, Technical Finish & Tillana Hold Strategy", "技巧舞步/结束/提拉纳保留策略" },
            { "Thrill Of Battle Heal Threshold", "战栗治疗阈值" },
            { "Try triple combo before embolden (You will need to get in melee range 17s before embolden is ready)", "在鼓励前尝试三连击（需要在鼓励就绪前 17 秒进入近战范围）" },
            { "Upper HP threshold you need to be to use Xenoglossy as a damage oGCD", "使用异言作为伤害能力技的自身 HP 上限" },
            { "Use 1st Potion at (value in seconds - leave at 0 if using in opener)", "第1瓶爆发药使用时机（秒，起手使用请设为0）" },
            { "Use 2nd Potion at (value in seconds)", "第2瓶爆发药使用时机（秒）" },
            { "Use 3rd Potion at (value in seconds)", "第3瓶爆发药使用时机（秒）" },
            { "Use Adloquium during the countdown opener", "倒计时起手中使用鼓舞激励之策" },
            { "Use AirAnchor at 1 second remaining on countdown", "倒计时剩余 1 秒时使用空气锚" },
            { "Use Aquaveil on other players", "对其他玩家使用水流幕" },
            { "Use Arkveld MegaPotion", "使用 Arkveld 大药水" },
            { "Use Asylum as soon as a single player heal (i.e. tankbusters) while moving, in addition to normal logic", "除正常逻辑外，移动中也可对单体治疗（如死刑）立即使用庇护所" },
            { "Use Bad Breath for AOE mitigation", "使用臭气进行 AOE 减伤" },
            { "Use Basic Instinct", "使用基础本能" },
            { "Use Bioblaster while moving", "移动中使用生化喷射" },
            { "Use Blessing", "使用祝福" },
            { "Use Bloodwhetting/Raw intuition on single enemies", "对单体敌人使用原初的血气/原初的直觉" },
            { "Use Cleansing", "使用净化" },
            { "Use Clemency with Requiescat", "安魂祈祷时使用深仁厚泽" },
            { "Use Clemency without Requiescat", "无安魂祈祷时使用深仁厚泽" },
            { "Use Communio immediately after Enshroud (For frontline)", "附体后立即使用大丰收（前线用）" },
            { "Use Countdown Ability (Fire 3)", "使用倒计时技能（火 3）" },
            { "Use Crimson Cyclone at any range, regardless of safety use with caution (Enabling this ignores the below distance setting).", "无视安全距离使用猩红旋风，慎用（启用后忽略下方距离设置）" },
            { "Use Crimson Cyclone at any range, regardless of saftey use with caution (Enabling this ignores the below distance setting).", "无视安全距离使用猩红旋风，慎用（启用后忽略下方距离设置）" },
            { "Use Crimson Cyclone when moving", "移动中使用猩红旋风" },
            { "Use DOT while moving even if it does not need refresh (disabling is a damage down)", "移动中使用 DOT 即使不需要刷新（禁用会损失输出）" },
            { "Use Dark Cannon or Shock Cannon in cases where the mob is immune to both blind and paralysis", "怪物免疫目盲和麻痹时使用暗炮/冲击炮" },
            { "Use Dark Cannon or Shock Cannon in cases where the mob is susceptible to both blind and paralysis", "怪物易受目盲和麻痹时使用暗炮/冲击炮" },
            { "Use Displacement after Engagement (use at own risk).", "交击斩后使用移转（风险自负）" },
            { "Use Dissipation during burst phases", "爆发阶段使用转化" },
            { "Use Divine Caress as soon as its available", "一有就用神爱抚" },
            { "Use Divine Veil during countdown", "倒计时中使用圣光幕帘" },
            { "Use Doom Spike for damage uptime if out of melee range even if it breaks combo", "远离近战范围时使用死天枪维持输出，即使断开连击" },
            { "Use Dragonfire Dive while moving", "移动中使用龙炎冲" },
            { "Use Earth's Reply if a hositle is within range", "有敌方在范围内时使用大地响应" },
            { "Use Earth's Reply if the status will end within the next GCD", "状态将在下一 GCD 内结束时使用大地响应" },
            { "Use Earthly Star as an attack while moving", "移动中将地星作为攻击使用" },
            { "Use Earthly Star during countdown timer.", "倒计时中使用地星" },
            { "Use Eukrasia Action to heal", "使用均衡技能治疗" },
            { "Use Eukrasia when out of combat", "脱战时使用均衡" },
            { "Use Eukrasian Prognosis during the countdown opener", "倒计时起手中使用均衡预后" },
            { "Use Forked Raiju instead of Fleeting Raiju if you are outside of range (Dangerous)", "超出范围时使用月影雷兽而非月影雷兽牙（危险）" },
            { "Use Form Shift", "使用演武" },
            { "Use GCDs to heal. (Ignored if there are no healers alive in party)", "使用 GCD 进行治疗（队内无其他存活治疗时忽略）" },
            { "Use GCDs to heal. (Ignored if you are the only healer in party)", "使用 GCD 进行治疗（队内仅有你一个治疗时忽略）" },
            { "Use Gemdraught/Tincture/pot", "使用爆发药" },
            { "Use Guardian freely", "自由使用守护" },
            { "Use Guardian with only Hallowed Ground", "仅与神圣领域同时使用守护" },
            { "Use Hagakure or Midare/Tendo Setsugekka when going from single target to AOE scenarios", "从单体切换到 AOE 场景时使用叶隐或纷乱雪月花/天道雪月花" },
            { "Use Hallowed Ground with Cover", "使用神圣领域+掩护" },
            { "Use Hide", "使用隐遁" },
            { "Use Holos as a heal when applicable", "适用时将整体论用作治疗" },
            { "Use Holy Spirit when out of melee range", "远离近战范围时使用圣灵" },
            { "Use HolyInWhite or CometInBlack while moving", "移动时使用白神圣/黑彗星" },
            { "Use Howling Fist/Enlightenment as a ranged attack verses single target enemies", "将空鸣拳/斗气斩作为远程攻击用于单体敌人" },
            { "Use Inner Release while moving", "移动中使用原初的解放" },
            { "Use Intervention on CoTank during tankbusters", "死刑时对副坦使用干预" },
            { "Use Invulnerability for Starfall", "使用无敌应对陨石冲击" },
            { "Use Kerachole as a heal when applicable", "适用时将坚角清汁用作治疗" },
            { "Use Leylines in combat when standing still", "战斗中静止时使用黑魔纹" },
            { "Use Lightspeed for movement (Still reserve for burst)", "移动时使用光速（仍保留爆发）" },
            { "Use Lily at max stacks/about to overcap.", "百合即将溢出时使用安慰之心" },
            { "Use Lily if about to overcap and no valid target nearby.", "即将溢出且附近无有效目标时使用安慰之心" },
            { "Use Low Chance abilities", "使用低概率技能" },
            { "Use Masterful Blitz abilites as soon as they are available.", "有必杀技就用" },
            { "Use Mighty Guard", "使用强力守护" },
            { "Use Mudras outside of combat when enemies are near", "敌人靠近时脱战使用忍术" },
            { "Use Oblation last stack of Oblation for party members", "保留最后一层献奉给队员" },
            { "Use Oblation on lowest HP party member during AOE scenarios", "AOE 场景中对最低 HP 队员使用献奉" },
            { "Use Opener Potion at minus (value in seconds)", "起手爆发药使用时机（开怪前秒数）" },
            { "Use Opener Potion at minus time in seconds", "起手爆发药使用时机（开怪前秒数）" },
            { "Use Opener Potion at minus time in seconds - only use if potting early in the opener", "起手爆发药使用时机（开怪前秒数，仅用于提前吃药的起手）" },
            { "Use Phantom Judgement", "使用幻影审判" },
            { "Use Physick above level 30", "30 级以上使用医术" },
            { "Use Pledge on self", "对自己使用信念" },
            { "Use Pray as a Heal", "将祈祷用作治疗" },
            { "Use Primal Rend while moving (Dangerous)", "移动中使用蛮荒崩裂（危险）" },
            { "Use Primal Rend while standing still outside of configured melee range (Dangerous)", "静止但超出配置近战范围时使用蛮荒崩裂（危险）" },
            { "Use Radiant Aegis on cooldown while in combat", "战斗中冷却好就用光明盾" },
            { "Use Raiton/Katon for uptime while disengaged (Moving one raiton/katon from 60s for uptime)", "远离目标时使用雷遁/火遁维持输出（将 60 秒循环中的一个雷遁/火遁用于输出）" },
            { "Use Rathalos MegaPotion", "使用雄火龙大药水" },
            { "Use Recitation during the countdown opener", "倒计时起手中使用复诵" },
            { "Use Recitation with Succor, Concitation, or Accession", "将复诵用于士气高扬之策、激励之策或异界的波动" },
            { "Use Retrace when out of Leylines in combat and standing still", "战斗中静止且离开黑魔纹时使用魔罩" },
            { "Use Rhizomata when out of combat", "脱战时使用根素" },
            { "Use Riddle of Fire after this ability", "在此技能后使用红莲体势" },
            { "Use Sacred Soil's regeneration as a healing effect", "将野战治疗阵的再生作为治疗效果使用" },
            { "Use Shadowstride in countdown", "倒计时中使用暗影步" },
            { "Use Sheltron at minimum X Oath to prevent over cap (Set to 0 to disable)", "忠义值达到 X 时使用盾阵防止溢出（设为 0 禁用）" },
            { "Use Snort to interrupt", "使用鼻息打断" },
            { "Use Stardiver while moving", "移动中使用坠星冲" },
            { "Use Starfall", "使用陨石冲击" },
            { "Use Suspend in combat", "战斗中使用暂停" },
            { "Use Suspend out of combat", "脱战时使用暂停" },
            { "Use Swift/Acceleration for oGCD window alignment (Fleche/Contre drift fix)", "使用即刻/促进对齐能力技窗口（修复飞刺/六分偏移）" },
            { "Use Swiftcast for movement", "使用即刻进行移动" },
            { "Use Swiftcast on Adloquium", "对鼓舞激励之策使用即刻" },
            { "Use Swiftcast on Garuda", "对迦楼罗使用即刻" },
            { "Use Swiftcast on Ruby Outburst when not enough level for Ruby Rite", "等级不足以使用赤红圣礼时对赤红暴发使用即刻" },
            { "Use Swiftcast on Ruby Rite if you are not high enough level for Garuda", "等级不足以使用迦楼罗时对赤红圣礼使用即刻" },
            { "Use Swiftcast on Ruby Ruin when not enough level for Ruby Rite", "等级不足以使用赤红圣礼时对赤红毁灭使用即刻" },
            { "Use Swiftcast on ressurection", "使用即刻进行复活" },
            { "Use Swiftcast on resurrection", "使用即刻进行复活" },
            { "Use The Blackest Night on lowest HP party member during AOE scenarios", "AOE 场景中对最低 HP 队员使用至黑之夜" },
            { "Use Tincture/Gemdraught when about to use Presence of Mind", "即将使用神速咏唱时使用爆发药" },
            { "Use Transfusion to heal", "使用输血治疗" },
            { "Use Transpose to Astral Fire before Paradox", "在悖论前使用星灵移位切换星极火" },
            { "Use Triple Cast for Blizzard 3 instant casts after transpose (false to save for movement only)", "星灵移位后用三连咏唱冰 3（关闭则仅保留给移动）" },
            { "Use Unhide", "使用解除隐蔽" },
            { "Use Variant Rampart on cooldown", "好了就用特殊要塞" },
            { "Use Vercure for Dualcast when out of combat.", "脱战时用赤治疗激活连续咏唱" },
            { "Use Warden's Paean on other players", "对其他玩家使用时神的加护" },
            { "Use Zoe during the countdown opener", "倒计时起手中使用活化" },
            { "Use a stack of Onslaught when its about to overcap while standing still", "静止时猛攻即将溢出则使用一层" },
            { "Use all Energy Drain During Burst", "爆发期间使用全部能量吸收" },
            { "Use both stacks of Leylines automatically", "自动使用两层黑魔纹" },
            { "Use both stacks of Lightspeed while moving", "移动时使用两层光速" },
            { "Use both stacks of Mudras", "使用两层忍术充能" },
            { "Use both stacks of Onslaught during burst while standing still", "静止时爆发中使用两层猛攻" },
            { "Use burst medicine in countdown (requires auto burst option on)", "倒计时中使用爆发药（需开启自动爆发选项）" },
            { "Use custom timing to refresh Death's Design", "使用自定义时间刷新死亡烙印" },
            { "Use first stack of Consolation ASAP when Seraph is out", "炽天使出场后立即使用第一层慰藉" },
            { "Use provoke in opening if tank stance is on", "坦克姿态开启时起手使用挑衅" },
            { "Use swiftcast for movement", "使用即刻进行移动" },
            { "Use swiftcast on Intercepted Rainbow Drip before Boss Untargetable", "在 Boss 不可选中前使用即刻彩虹点滴" },
            { "Use swiftcast on Motif", "使用即刻绘制" },
            { "Use swiftcast on Rainbow Drip (Priority over below settings)", "使用即刻彩虹点滴（优先级高于以下设置）" },
            { "Use the balance Opener in High-End Duties", "在高难任务中使用 The Balance 起手" },
            { "Use the paint overcap protection (will still use comet while moving if the setup is on)", "使用颜料溢出保护（开启时移动中仍会使用彗星）" },
            { "Use this if there's no other raid buff in your party", "队内无其他团队增益时使用此选项" },
            { "Use up all charges of Uncoiled Fury if you have used Tincture/Gemdraught (Overrides next option)", "使用爆发药后倾泻全部蛇尾术充能（覆盖下一选项）" },
            { "Use up both stacks of Intervene during burst window", "爆发窗口中使用两层突进" },
            { "Wanderer's Minuet Uptime", "放浪神小步舞曲持续时间" },
            { "When to use Burst", "爆发使用时机" },
            { "When to use Opener", "起手使用时机" },
            { "Which Abilities for burst to manage", "管理哪些爆发技能" },
            { "Which Motif to use swiftcast on", "对哪个构想使用即刻" },
            { "Which Opener to Use", "选择起手" },
            { "Which Opener to use", "选择起手" },
            { "Which opener to use", "选择起手" },
            { "Your HP percentage needed to use Occult Chakra", "使用神秘查克拉所需的自身 HP 百分比" },
            { "Your MP needed to use Occult Chakra", "使用神秘查克拉所需的自身 MP" },
        };

        /// <summary>
        /// Gets the Chinese translation for a RotationConfig display name.
        /// Returns the English original on non-Chinese clients or when no translation exists.
        /// </summary>
        public static string TryGetChinese(string englishName)
        {
            if (!Service.IsChineseClient)
            {
                return englishName;
            }

            var normalized = englishName.Replace("\r\n", "\n");
            if (_translations.TryGetValue(normalized, out var chinese))
            {
                return chinese;
            }

            string? longestPrefix = null;
            string? longestTranslation = null;
            var consumedLength = 0;
            foreach (var translation in _translations)
            {
                if (!translation.Key.EndsWith('\n') ||
                    longestPrefix != null && translation.Key.Length <= longestPrefix.Length)
                {
                    continue;
                }

                if (englishName.StartsWith(translation.Key, StringComparison.Ordinal))
                {
                    longestPrefix = translation.Key;
                    longestTranslation = translation.Value;
                    consumedLength = translation.Key.Length;
                    continue;
                }

                var crlfPrefix = translation.Key.Replace("\n", "\r\n");
                if (englishName.StartsWith(crlfPrefix, StringComparison.Ordinal))
                {
                    longestPrefix = translation.Key;
                    longestTranslation = translation.Value;
                    consumedLength = crlfPrefix.Length;
                }
            }

            if (longestTranslation != null)
            {
                return longestTranslation + englishName[consumedLength..];
            }

            return englishName;
        }
    }
}
